### ISSUE TITLE
Email params

### ISSUE THREAD

**Issue by andresmafra** [exesse/mongodump-s3#153]
Hello, great job my friend.

A question, how can I send an email without authentication? Do you have an example of a SMTP server without it?

thanks!

**Comment by exesse** [comment]
Hi @andresmafra,
it depends:

- if you want to usethe tool as a CLI you may setup [postfix](https://unix.stackexchange.com/questions/13995/configure-postfix-to-send-and-receive-to-and-from-localhost) as smpt relay.
- if you are using Docker you may be interested in looking at [this](https://hub.docker.com/r/namshi/smtp/) for example.

**Comment by andresmafra** [comment]
So cool, I will take a look!
thanks @exesse
