### ISSUE TITLE
Add support for AWS S3 PATH

### ISSUE THREAD

**Issue by MiticoBerna** [exesse/mongodump-s3#154]
Hi, great job!

I would ask to you if is it possibile to add the S3 PATH, because I have others database backups inside of the same bucket.

Would be great a new env var like: MONGO_DUMP_BUCKET_PATH

Is it feasible for you?

Many thanks

**Comment by exesse** [comment]
Hi @MiticoBerna,

Sure, I could add this

**Comment by exesse** [comment]
Hi @MiticoBerna,

It is already supported. Please pass ENV variables:

```
MONGO_DUMP_BUCKET=
MONGO_OUTPUT_FOLDER=
```
